name: Deploy React Microfrontend

on:
  push:
    branches:
      - main  # Runs on every push to main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Build React Microfrontend
        run: npm run build

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Upload Build to S3
        run: aws s3 cp dist/react-microfrontend.js s3://react-microfrontend-bucket-c738233a/

      - name: Invalidate CloudFront Cache
        run: aws cloudfront create-invalidation --distribution-id E1HRJYICKM2WAD --paths "/*"
